#
# * Config
# * Stores static configuration and project info
# *
# * Copyright Â© SoftLayer, an IBM Company
# * Released under the MIT license
#

# ==============================
# Tags
# ==============================

company:
  official:   IBM Corporation
  shorthand:  IBM

div:
  official:   IBM Cloud
  group:      SoftLayer Development
  tagline:    "Closing the gap between users and technology."

team:
  arch:       Architecture
  engr:       Engineering
  open:       Open Technology

section:
  arch:       architecture
  engr:       engineering
  open:       open-technology

job:
  arch:       Software Architect
  engr:       Software Engineer
  prod:       Product Manager

# ==============================
# Server
# ==============================

permalink:    pretty
exclude:      [".gitignore", "Gemfile", "LICENSE", "README.md"]

gems:
  - jekyll-sitemap
